# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  test-log-ui:
    image: viniciuscluna/test-log-ui
    ports:
      - "5173:5173"
  docker-api:
    image: viniciuscluna/test-log-api
    ports:
      - "5160:80"    